project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - index-pdf.qmd
    - slides.qmd
    - assignments.qmd

  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - exercises/*.pdf

website:
  title: ""
  search: false
  navbar:
    search: false
    title: BUSI 722
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
