project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - index-pdf.qmd
    - slides.qmd
    - assignments.qmd
    - exercises/exercise1a.qmd
    - exercises/exercise1b.qmd
    - exercises/exercise1c.qmd
    - exercises/exercise1d.qmd
    - exercises/exercise2a.qmd
    - exercises/exercise2b.qmd
    - exercises/exercise2c.qmd
    - exercises/exercise2d.qmd
    - exercises/exercise3a.qmd
    - exercises/exercise3b.qmd
    - exercises/exercise3c.qmd
    - exercises/exercise3d.qmd
    - exercises/exercise4a.qmd
    - exercises/exercise4b.qmd
    - exercises/exercise4c.qmd
    - exercises/exercise4d.qmd
    - exercises/exercise5a.qmd
    - exercises/exercise5b.qmd
    - exercises/exercise5c.qmd
    - exercises/exercise5d.qmd
    - exercises/exercise6a.qmd
    - exercises/exercise6b.qmd
    - exercises/exercise6c.qmd
    - exercises/exercise6d.qmd

  resources:
    - CNAME
    - .nojekyll
    - slides/*.pdf
    - exercises/*.pdf

website:
  title: ""
  search: false
  navbar:
    search: false
    title: BUSI 722
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true

comments:
  hypothesis: true
